export enum ActionType {
  Attendance = "Attendance",
  Homework = "Homework",
  Score = "Score",
  State = "State",
  CreatePost = "CreatePost",
  CreateProject = "CreateProject",
  InteractLike = "InteractLike",
  NetWorth = "NetWorth",
  Achievement = "Achievement",
  OutstandingSpeaker = "OutstandingSpeaker",
  GroundbreakingIdea = "GroundbreakingIdea",
  RealWorldApplication = "RealWorldApplication",
  InteractComment = "InteractComment",
  ReceiveLikes = "ReceiveLikes",
  AddFriend = "AddFriend",
  DailyLogin = "DailyLogin",
  CollectItems = "CollectItems",
  CompleteQuests = "CompleteQuests",
  SharePost = "SharePost",
  QualityPost = "QualityPost",
  Participation = "Participation",
  GroupDiscussion = "GroupDiscussion",
  ResourceAccess = "ResourceAccess",
  CompleteProfile = "CompleteProfile",
  MentorSession = "MentorSession",
  CreatePortfolio = "CreatePortfolio",
  PeerSupport = "PeerSupport",
  // Custom = "Custom",
}

export const ActionTypeMap: { value: string; label: string }[] = [
  { value: ActionType.Attendance.toString(), label: "Điểm danh" },
  { value: ActionType.Homework.toString(), label: "Bài tập về nhà" },
  { value: ActionType.Score.toString(), label: "Điểm số" },
  { value: ActionType.State.toString(), label: "Trạng thái học tập" },
  { value: ActionType.CreatePost.toString(), label: "Tạo bài viết" },
  { value: ActionType.CreateProject.toString(), label: "Tạo dự án" },
  { value: ActionType.InteractLike.toString(), label: "Thả tim" },
  { value: ActionType.NetWorth.toString(), label: "Sở hữu tiền" },
  { value: ActionType.Achievement.toString(), label: "Thành tựu" },
  {
    value: ActionType.OutstandingSpeaker.toString(),
    label: "Phát biểu nổi bật",
  },
  { value: ActionType.GroundbreakingIdea.toString(), label: "Ý tưởng đột phá" },
  {
    value: ActionType.RealWorldApplication.toString(),
    label: "Ứng dụng thực tế",
  },
  { value: ActionType.InteractComment.toString(), label: "Bình luận" },
  { value: ActionType.ReceiveLikes.toString(), label: "Lượt thích nhận được" },
  { value: ActionType.AddFriend.toString(), label: "Kết bạn" },
  { value: ActionType.DailyLogin.toString(), label: "Đăng nhập mỗi ngày" },
  { value: ActionType.CollectItems.toString(), label: "Thu thập vật phẩm" },
  { value: ActionType.CompleteQuests.toString(), label: "Hoàn thành nhiệm vụ" },
  { value: ActionType.SharePost.toString(), label: "Chia sẻ bài viết" },
  { value: ActionType.QualityPost.toString(), label: "Bài viết chất lượng" },
  {
    value: ActionType.Participation.toString(),
    label: "Tham gia xây dựng bài",
  },
  { value: ActionType.GroupDiscussion.toString(), label: "Thảo luận nhóm" },
  { value: ActionType.ResourceAccess.toString(), label: "Truy cập tài nguyên" },
  { value: ActionType.CompleteProfile.toString(), label: "Hoàn thiện hồ sơ" },
  { value: ActionType.MentorSession.toString(), label: "Buổi mentoring" },
  { value: ActionType.CreatePortfolio.toString(), label: "Tạo portfolio" },
  { value: ActionType.PeerSupport.toString(), label: "Hỗ trợ bạn bè" },
  // { value: ActionType.Custom.toString(), label: "Tùy chỉnh" },
];
